### PR TITLE
All Commits

### PR DESCRIPTION
**Pull request by Voltern**

### CODE REVIEW

**Comment by VutonDesign** [comment]
@Voltern What is this for?

**Comment by Voltern** [comment]
Just To Mark All Your Commits, Don't Merge, Just Keep It ope, Your commits get added whenever you make 
a change.

**Comment by VutonDesign** [comment]
I'm going to close it because I can just look at the Commits tab.

**Comment by Hexsphere** [comment]
Yeah

**Comment by VutonDesign** [comment]
😄

**Pull request closed without merging**
